Add test for adding a single number
This is the sixth step in the JavaScript Test-Driven Development demo.

This new test fails because the existing implementation of
ProdStringCalculator.add() always returns zero:

   ❯ components/prod-calculator.test.js (2)
     ❯ ProdStringCalculator (2)
       ✓ empty string returns zero
       × single number returns same number

  ---- Failed Tests 1 ----

   FAIL  components/prod-calculator.test.js > ProdStringCalculator > single number returns same number
  AssertionError: expected +0 to deeply equal 1

  - Expected
  + Received

  - 1
  + 0

   ❯ components/prod-calculator.test.js:25:20
       23|     let result = calc.add('1')
       24|
       25|     expect(result).toEqual(1)
         |                    ^
       26|   })
       27| })

  ---- [1/1] ----

   Test Files  1 failed | 6 passed (7)
        Tests  1 failed | 18 passed (19)

Now we're ready to add just enough code to get the test to pass.