Add test for adding a single number
This is the sixth step in the Java Test-Driven Development demo.

This new test fails because the existing implementation of
ProdStringCalculator.add() always returns zero:

  > Task :strcalc:test FAILED

  ProdStringCalculatorTest > singleNumberReturnsSameNumber() FAILED
      org.opentest4j.AssertionFailedError at ProdStringCalculatorTest.java:29

  3 tests completed, 1 failed

  FAILURE: Build failed with an exception.

The corresponding test log shows:

  org.opentest4j.AssertionFailedError: expected: <1> but was: <0>

Now we're ready to add just enough code to get the test to pass.