Bump frontend packages, fix browser test
The browser tests were failing with the following because the
chrome-for-testing version had moved on since the last webdriverio bump:

  Error: Failed downloading chromedriver v122.0.6261.94: Download failed:
  server returned code 404. URL:
  https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/122.0.6261.94/mac-arm64/chromedriver-mac-arm64.zip,
  retrying ...