Add test for adding two numbers
This is the eighth step in the JavaScript Test-Driven Development demo.

The new "ProdStringCalculatorTest > returns sum of two numbers" fails
because the current ProdStringCalculator.add() implementation passes the
input string to Integer.parseInt() without breaking it apart:

   ❯ components/prod-calculator.test.js (3)
     ❯ ProdStringCalculator (3)
       ✓ empty string returns zero
       ✓ single number returns same number
       × returns sum of two numbers

  ---- Failed Tests 1 ----

   FAIL  components/prod-calculator.test.js > ProdStringCalculator > returns sum of two numbers
  AssertionError: expected 1 to deeply equal 3

  - Expected
  + Received

  - 3
  + 1

   ❯ components/prod-calculator.test.js:33:20
       31|     let result = calc.add('1,2')
       32|
       33|     expect(result).toEqual(3)
         |                    ^
       34|   })
       35| })

  ---- [1/1] ----

   Test Files  1 failed | 6 passed (7)
        Tests  1 failed | 19 passed (20)

Now we're ready to add just enough code to make the test pass again.