Instantiate ProdStringCalculator in test
This is the second step in the Java Test-Driven Development demo.

Instantiating the nonexistent ProdStringCalculator class causes
ProdStringCalculatorTest.emptyStringReturnsZero() to fail to build:

  > Task :strcalc:compileTestJava FAILED
  .../ProdStringCalculatorTest.java:14: error: cannot find symbol
          var calc = new ProdStringCalculator();
                         ^
    symbol:   class ProdStringCalculator
    location: class ProdStringCalculatorTest
  1 error

  FAILURE: Build failed with an exception.

For the purposes of Test-Driven Development, build failures are test
failures.

Now we're ready to create an empty ProdStringCalculator class to make
the test pass.