Instantiate ProdStringCalculator in test
This is the second step in the JavaScript Test-Driven Development demo.

Instantiating the nonexistent ProdStringCalculator class causes
"ProdStringCalculator > empty string returns zero" to fail to build:

   ❯ components/prod-calculator.test.js (1)
     ❯ ProdStringCalculator (1)
       × empty string returns zero

  ---- Failed Tests 1 ----

   FAIL  components/prod-calculator.test.js > ProdStringCalculator > empty string returns zero
  ReferenceError: ProdStringCalculator is not defined
   ❯ components/prod-calculator.test.js:13:16
       11| describe('ProdStringCalculator', () => {
       12|   test('empty string returns zero', () => {
       13|     let calc = new ProdStringCalculator()
         |                ^
       14|   })
       15| })

  ---- [1/1] ----

   Test Files  1 failed | 6 passed (7)
        Tests  1 failed | 17 passed (18)

For the purposes of Test-Driven Development, build failures are test
failures.

Now we're ready to create an empty ProdStringCalculator class to make
the test pass.