Add workflow_run.id to actions/download-artifact
The addition of actions/download-artifact@v4 to
publish-test-results.yaml in #66 still failed:

- https://github.com/mbland/tomcat-servlet-testing-example/actions/runs/7267779677/job/19802307107

What was interesting was the `run-id:` value from the "Download test
results" step:

  Run actions/download-artifact@v4
    with:
      name: test-results
      merge-multiple: false
      repository: mbland/tomcat-servlet-testing-example
      run-id: 7267779677
  Downloading single artifact
  Error: Unable to download artifact(s): Artifact not found for name:
    test-results

followed by this line from "Post test report":

  Action was triggered by workflow_run: using SHA and RUN_ID from
  triggering workflow

So this change attempts to fix the breakage by adding
`github.event.workflow_run.id` to the actions/download-artifact
configuration.