Replace test/page-loader.js with test-page-opener
Required adding test-page-opener to the test.server.deps.inline
config variable. Also updated all internal import paths to end with the
'.js' extension.

These changes were a consequence of the fact that the previous
test/page-loader.js file was automatically bundled via Rollup, and the
"external" test-page-opener isn't by default. Without bundling,
test-page-opener can't resolve Handlebars modules transformed via
rollup-plugin-handlebars-precompiler.

---

On first adding test-page-opener to the project, running main.test.js in
the browser passed. When running it in Node, all of the internal imports
that didn't end with '.js' failed. This followed on the heels of
mbland/test-page-opener#20, which I created when test-page-opener's own
internal imports failed when used in this project. (I also filed
mbland/test-page-opener#21 when its internal istanbul-lib-coverage
import broke in this project, too.)

After updating all the local imports on .js files, the Handlebars
imports (ending in '.hbs') continued to fail with
ERR_UNKNOWN_FILE_EXTENSION:

```sh
% pnpm test -- run main.test.js

 RUN  v1.1.3 /.../tomcat-servlet-testing-example/strcalc/src/main/frontend

 ❯ main.test.js (1)
   ❯ String Calculator UI on initial page load (1)
     × contains the "Hello, World!" placeholder

—— Failed Tests 1 ——

 FAIL  main.test.js > String Calculator UI on initial page load > contains the "Hello, World!" placeholder
Error: opening index.html
 ❯ JsdomPageOpener.open node_modules/.pnpm/test-page-opener@1.0.3/node_modules/test-page-opener/lib/jsdom.js:85:13
 ❯ TestPageOpener.open node_modules/.pnpm/test-page-opener@1.0.3/node_modules/test-page-opener/index.js:109:18
 ❯ main.test.js:18:26
     16|
     17|   test('contains the "Hello, World!" placeholder', async () => {
     18|     const { document } = await opener.open('index.html')
       |                          ^
     19|     const appElem = document.querySelector('#app')
     20|

Caused by: Error: importing file:///.../tomcat-servlet-testing-example/strcalc/src/main/frontend/main.js
 ❯ node_modules/.pnpm/test-page-opener@1.0.3/node_modules/test-page-opener/lib/jsdom.js:173:25
 ❯ importModulesOnEvent node_modules/.pnpm/test-page-opener@1.0.3/node_modules/test-page-opener/lib/jsdom.js:131:15

Caused by: TypeError: Unknown file extension ".hbs" for
/.../mbland/tomcat-servlet-testing-example/strcalc/src/main/frontend/components/calculator.hbs
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
Serialized Error: { code: 'ERR_UNKNOWN_FILE_EXTENSION' }
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
```

(I'm rather relieved to have implemented mbland/test-page-opener#14 just
today, which is why there are such nice "Caused by:" messages above.)

When I temporarily replaced the npm dependency with my local working
copy via `pnpm link ../../../../../test-page-opener`, the test would
pass again.

It occurred to me that the Node runs of the test weren't including
test-page-opener in the Rollup bundle containing the transformed .hbs
files. Or, it would include it when it was linked to the local copy, but
not include it when installed normally.

I eventually figured out that the Vitest config setting
server.deps.inline would cause the "external" test-page-opener to get
bundled, enabling it to resolve the '.hbs' imports.

- <https://vitest.dev/config/#server-deps-inline>